#!/usr/bin/bash

z
# notification daemon
dunst &



# other
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
notify-send -a aurora "Hello $(whoami)" &
# ~/Dotfiles/waybar/hotreload.sh
